### ISSUE TITLE
[Bug Report]: 1.21 break

### ISSUE THREAD

**Issue by Drejky** [Aurealis-Graphics/Lux-Shader#17]
### Describe the bug

Shader doesn't load on new version (works fine on 1.20.x). Throws following Iris error:
```bash
deferred.fsh: deferred.fsh: 0(348) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(348) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(349) : error C0000: syntax error, unexpected "=", expecting "::" at token "="
0(350) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(351) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"
0(353) : error C0000: syntax error, unexpected '=', expecting "::" at token "="
0(354) : error C0000: syntax error, unexpected "=", expecting "::" at token "="
0(355) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(356) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"
```

### To reproduce

1. Load minecraft 1.21
2. Enable Lux 1.1 patch 1

### Hardware specification

- Nvidia RTX 4060m
- AMD Ryzen 5 7535HS

### Software specification

- Iris 1.2.1 +mc1.21
- Sodium 0.5.9 +mc1.21
- Java version 21.0.2

### Additional context

My favourite shader <3 take your time updating it, you are doing a great job

**Comment by TechDevOnGitHub** [comment]
Fixed the issue on my end. Here's Lux running on the new 1.21 Iris version:

![2024-07-02_00 57 39](https://github.com/Aurealis-Graphics/Lux-Shader/assets/65711173/f4ab7769-634e-4b2b-b51f-af2d85e8fa0e)

_Feel free to repoen the issue if it persists on your end._
